=begin
#Payment Gateway API Specification.

#Payment Gateway API for payment processing. Version 6.4.0.20181018.001 

OpenAPI spec version: 6.4.0.20181018.001

Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

require 'date'

module OpenapiClient
  class TransactionOrigin
    
    ECOM = 'ECOM'.freeze
    MAIL = 'MAIL'.freeze
    PHONE = 'PHONE'.freeze
    RETAIL = 'RETAIL'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TransactionOrigin.constants.select { |c| TransactionOrigin::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TransactionOrigin" if constantValues.empty?
      value
    end
  end
end
