=begin
#Payment Gateway API Specification.

#Payment Gateway API for payment processing. Version 6.4.0.20181018.001 

OpenAPI spec version: 6.4.0.20181018.001

Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PaymentSchedulesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentSchedulesApi' do
  before do
    # run before each test
    @instance = OpenapiClient::PaymentSchedulesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentSchedulesApi' do
    it 'should create an instance of PaymentSchedulesApi' do
      expect(@instance).to be_instance_of(OpenapiClient::PaymentSchedulesApi)
    end
  end

  # unit tests for cancel_payment_schedule
  # Cancel a gateway payment schedule.
  # Use this to cancel an existing gateway payment schedule.
  # @param content_type content type
  # @param client_request_id A client-generated ID for request tracking and signature creation, unique per request.  This is also used for idempotency control. We recommend 128-bit UUID format.
  # @param api_key 
  # @param timestamp Epoch timestamp in milliseconds in the request from a client system. Used for Message Signature generation and time limit (5 mins).
  # @param order_id Gateway order identifier as returned in the parameter orderId
  # @param [Hash] opts the optional parameters
  # @option opts [String] :message_signature Used to ensure the request has not been tampered with during transmission. The Message-Signature is the Base64 encoded HMAC hash (SHA256  algorithm with the API Secret as the key.) For more information, refer to the supporting documentation on the Developer Portal.
  # @option opts [String] :region The region where client wants to process the transaction
  # @option opts [String] :store_id An optional outlet ID for clients that support multiple stores in the same developer app
  # @return [PaymentSchedulesResponse]
  describe 'cancel_payment_schedule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_payment_schedule
  # Use this to create a gateway payment schedule.
  # This can be used to create a gateway payment schedule.
  # @param content_type content type
  # @param client_request_id A client-generated ID for request tracking and signature creation, unique per request.  This is also used for idempotency control. We recommend 128-bit UUID format.
  # @param api_key 
  # @param timestamp Epoch timestamp in milliseconds in the request from a client system. Used for Message Signature generation and time limit (5 mins).
  # @param payment_schedules_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :message_signature Used to ensure the request has not been tampered with during transmission. The Message-Signature is the Base64 encoded HMAC hash (SHA256  algorithm with the API Secret as the key.) For more information, refer to the supporting documentation on the Developer Portal.
  # @option opts [String] :region The region where client wants to process the transaction
  # @return [PaymentSchedulesResponse]
  describe 'create_payment_schedule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for inquiry_payment_schedule
  # View a gateway payment schedule.
  # This can be used to view an existing gateway payment schedule.
  # @param content_type content type
  # @param client_request_id A client-generated ID for request tracking and signature creation, unique per request.  This is also used for idempotency control. We recommend 128-bit UUID format.
  # @param api_key 
  # @param timestamp Epoch timestamp in milliseconds in the request from a client system. Used for Message Signature generation and time limit (5 mins).
  # @param order_id Gateway order identifier as returned in the parameter orderId
  # @param [Hash] opts the optional parameters
  # @option opts [String] :message_signature Used to ensure the request has not been tampered with during transmission. The Message-Signature is the Base64 encoded HMAC hash (SHA256  algorithm with the API Secret as the key.) For more information, refer to the supporting documentation on the Developer Portal.
  # @option opts [String] :region The region where client wants to process the transaction
  # @option opts [String] :store_id An optional outlet ID for clients that support multiple stores in the same developer app
  # @return [RecurringPaymentDetailsResponse]
  describe 'inquiry_payment_schedule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_payment_schedule
  # Update a gateway payment schedule.
  # This can be used to update a gateway payment schedule.
  # @param content_type content type
  # @param client_request_id A client-generated ID for request tracking and signature creation, unique per request.  This is also used for idempotency control. We recommend 128-bit UUID format.
  # @param api_key 
  # @param timestamp Epoch timestamp in milliseconds in the request from a client system. Used for Message Signature generation and time limit (5 mins).
  # @param order_id Gateway order identifier as returned in the parameter orderId
  # @param payment_schedules_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :message_signature Used to ensure the request has not been tampered with during transmission. The Message-Signature is the Base64 encoded HMAC hash (SHA256  algorithm with the API Secret as the key.) For more information, refer to the supporting documentation on the Developer Portal.
  # @option opts [String] :region The region where client wants to process the transaction
  # @option opts [String] :store_id An optional outlet ID for clients that support multiple stores in the same developer app
  # @return [PaymentSchedulesResponse]
  describe 'update_payment_schedule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
