=begin
#Payment Gateway API Specification.

#Payment Gateway API for payment processing. Version 6.4.0.20181018.001 

OpenAPI spec version: 6.4.0.20181018.001

Generated by: https://openapi-generator.tech
OpenAPI Generator version: unset

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CardInfo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CardInfo' do
  before do
    # run before each test
    @instance = OpenapiClient::CardInfo.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CardInfo' do
    it 'should create an instance of CardInfo' do
      expect(@instance).to be_instance_of(OpenapiClient::CardInfo)
    end
  end
  describe 'test attribute "brand"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "brand_product_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "card_function"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["credit", "debit", "prepaid", "voucher", "undefined"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.card_function = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "commercial_card"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["CORPORATE", "NON_CORPORATE"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.commercial_card = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "issuer_country"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "issuer_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
