=begin
#Payment Gateway API Specification

#Payment Gateway API for payment processing. 

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::PaymentSchedulesResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaymentSchedulesResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::PaymentSchedulesResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentSchedulesResponse' do
    it 'should create an instance of PaymentSchedulesResponse' do
      expect(@instance).to be_instance_of(SwaggerClient::PaymentSchedulesResponse)
    end
  end
  describe 'test attribute "client_request_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "api_trace_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "transaction_status"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["SUCCESS", "VALIDATION_FAILED", "PROCESSING_FAILED", "FAILURE"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.transaction_status = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "order_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

