=begin
#Payment Gateway API Specification

#Payment Gateway API for payment processing. 

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::PaymentCardAuthenticationRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaymentCardAuthenticationRequest' do
  before do
    # run before each test
    @instance = SwaggerClient::PaymentCardAuthenticationRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentCardAuthenticationRequest' do
    it 'should create an instance of PaymentCardAuthenticationRequest' do
      expect(@instance).to be_instance_of(SwaggerClient::PaymentCardAuthenticationRequest)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["SECURE_3D"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.type = value }.not_to raise_error
       #end
    end
  end

end

