=begin
#Payment Gateway API Specification

#Payment Gateway API for payment processing. 

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::TransactionResponseAuthenticationRedirectParams
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TransactionResponseAuthenticationRedirectParams' do
  before do
    # run before each test
    @instance = SwaggerClient::TransactionResponseAuthenticationRedirectParams.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionResponseAuthenticationRedirectParams' do
    it 'should create an instance of TransactionResponseAuthenticationRedirectParams' do
      expect(@instance).to be_instance_of(SwaggerClient::TransactionResponseAuthenticationRedirectParams)
    end
  end
  describe 'test attribute "pa_req"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "term_url"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "md"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

